---
- name: EC2 | create ec2 instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ aws_ssh_key }}"
    group: "{{ aws_security_group }}"
    instance_type: "{{ aws_instance_type }}"
    image: "{{ aws_instance_images }}"
    wait: yes
    wait_timeout: 500
    count: 1
    volumes:
      - device_name: "{{ aws_instance_vol }}"
        volume_type: "{{ aws_vol_type }}"
        volume_size: "{{ aws_vol_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ aws_subnet_id }}"
    instance_initiated_shutdown_behavior: stop
    assign_public_ip: yes
    region: "{{ aws_instance_region }}"
    zone: "{{ aws_instance_zone }}"
    instance_tags:
      Name: "{{ item }}"
      type: ansible_created
  register: ec2
  with_sequence: start={{ instances_info.start }} end={{ instances_info.end }} format={{ host_prefix }}-{{ instances_info.name }}-%02x

- name: EC2 | add host
  add_host:
    hostname: "{{ item.instances[0].public_ip }}"
    groupname: launched
    tag: "{{ item.instances[0].tags.Name }}"
  with_items: "{{ ec2.results }}"

- name: EC2 | wait for ec2 instance
  wait_for: 
    host: "{{ item.instances[0].public_ip }}"
    port: 22
    delay: 20
    timeout: 400
    state: started
  with_items: "{{ ec2.results }}"

- name: debug
  debug:
    var: "{{ ec2.results }}"
